### PR TITLE
typed Timestamp2

### PR DESCRIPTION
**Pull request by shlomi-noach**
`decodeTimestamp2` only returns a string when the column value was `0000-00-00 00:00:00`. Otherwise -- when it is a "real" timestamp value, the function returns the `time.Time` type.

This allows us to retain the metadata associated with the value, i.e. timezone.
It also allows us to easily recognize a timestamp value where previously the `string` type would obscure the real column type.

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @shlomi-noach 

I need to see whether this change will affect other programs or not first. /cc @qiuyesuifeng

**Comment by shlomi-noach** [comment]
@siddontang I understand. If you like, I can resubmit this PR with an optional flag, such that only upon some `ParseTimestamp2AsTimeType = true` will this behave as I suggested. This will ensure backwards compatibility. WDYT?

**Comment by siddontang** [comment]
Hi @shlomi-noach 

I prefer returning Time here, no need another option.

**Comment by siddontang** [comment]
Hi @shlomi-noach 

We still need the configuration for backward-compatibility. :-) 
Maybe you can do in the same PR here.

**Comment by siddontang** [comment]
Although I prefer Time, I must guarantee our own programs can run correctly.

**Comment by shlomi-noach** [comment]
Let's begin with a conditional, and later you can decide at your own leisure. Updating the PR.

**Comment by shlomi-noach** [comment]
hmmm. Gonna close this one and open a new PR. Can ride same PR from fork.

**Comment by shlomi-noach** [comment]
replaced by https://github.com/siddontang/go-mysql/pull/86

**Pull request closed without merging**
