### PR TITLE
*: use ErrorEqual to check error.

### PR DESCRIPTION
**Pull request by siddontang**
We use juju errors, so can' use `==` and `!=` to check error directly. 

@qiuyesuifeng

### CODE REVIEW

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by siddontang** [comment]
For https://github.com/siddontang/go-mysql/issues/50 @zhapuyu

**Comment by siddontang** [comment]
Hi @shlomi-noach

Now I will update go-mysql, if breaks your project, please tell me.

**Comment by shlomi-noach** [comment]
@siddontang thank youl I'm using `go-mysql` statically and so am at this time not pulling any updates.

**Pull request merged**
