### PR TITLE
should be possible to exit from processing file when conditions met

### PR DESCRIPTION
**Pull request by svart-ravn**
- adding propery 'exit bool';
- adding function SetExit to control it.

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @svart-ravn 

Can you tell me why do you want to support it?

**Comment by svart-ravn** [comment]
I need to have it because I want to parse part of a binary logs. For example for a specific period of time or certain amount of transactions. And on the other hand I do not need to process the whole file so it means that I need to have any switch to break from processing.

I did not find any way how to do it so here is the pull request. If you have any idea how to implement it easily without killing goroutine it would be good to know.

**Comment by siddontang** [comment]
@svart-ravn 
IMO, mostly if you want to support cancel + timeout feature, it is better to pass a context to the function. You can try it.

**Comment by siddontang** [comment]
The code may like:

```go
for {
    select {
        case <-ctx.Done():
             return
        default:
             break
    }
}
```

**Comment by svart-ravn** [comment]
I thought context will be a bit over-engineering for this feature. I do not need to pass variables, no need to have a timeout, there is no async processing and I can hardly believe that it will be required. But if you insist on context - ok, I can do it in this way

**Comment by siddontang** [comment]
Hi @svart-ravn 

What I mean is passing the context as the ParseReader argument, it is not a good style to embed the context and reset from outside directly.

**Comment by siddontang** [comment]
Another way I guess we can support a Stop function for the parser instead of SetExit.

**Comment by svart-ravn** [comment]
`Stop` function for me is almost the same like `SetExit` just another name for the same functionality. I will have the name 'exit` property in a different way. Do you agree on that?

something like this:

```
... struct {
 ...
  stopProcessing bool
}

func Stop(){
   p.stop = true
}

func ParseReader (){
    for {
      if stopProcessing {
       break
      }
    }
}


func ParseFile (){
   p.stopProcessing = false
}
```

**Comment by siddontang** [comment]
@svart-ravn 

It is not thread-safe, you must use atomic var here, others LGTM.

**Comment by svart-ravn** [comment]
is it possible to use sync.mutex.lock() instead of atomic vars? sync/atomic does not support boolean and sync/mutex will keep code clean and simple.

**Comment by siddontang** [comment]
you can use atomic i32 or i64 or others, to check 0 and 1.

**Comment by siddontang** [comment]
It is heavy to use a Mutex for a var.

**Comment by siddontang** [comment]
Thanks @svart-ravn

**Pull request merged**
