### PR TITLE
*: support re-sync when connection was bad.

### PR DESCRIPTION
**Pull request by siddontang**
@qiuyesuifeng

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @shlomi-noach

For https://github.com/siddontang/go-mysql/issues/43

**Comment by shlomi-noach** [comment]
:+1: is there a difference in usage? Can you document a usage example?

**Comment by siddontang** [comment]
The big difference is that now you could create the syncer with a config, then start it, like:
```
cfg := &BinlogSyncerConfig{
   Host: "127.0.0.1",
   Port: 3306,
   User: "root",
   Password: "",
   ServerID: 101,
   // more ...
}

syncer := NewBinlogSyncer(&cfg);
stream, _ := syncer.StartSync(position);

for {
     event, err := stream.GetEvent()
}
```

We will handle reconnection when the sync connection broken.

**Comment by qiuyesuifeng** [comment]
LGTM

**Pull request merged**
