### PR TITLE
Expose the ability to parse more data without calling *BinlogParser.Reset()

### PR DESCRIPTION
**Pull request by apokalyptik**
The purpose of this patch is to allow for parsing data in small chunks without the need to have a FORMAT_DESCRIPTION_EVENT (FDE) in each chunk (especially for readers.)  

The change here should be backwards compatible, as the original code paths all still do exactly what they did before. Reset() included.  I didn't want to change this because the Reset() actually came in a fix to an issue (I think?) #75 which had nothing in the way of workable details to understand.  So rather than risk a regression about something important I thought to expose new functionality for the use case.

The use case for something like this is, for example, when you're tailing the live reply-logs from a MySQL Slave and you want to only keep up with the replication thread. It then becomes necessary to provide small chunks of data to the parser at a time. The problem is that ParseReader calls Reset() which clears the stored FDE.  Rather than try and do something crazy it seemed that a codepath which just avoided this would be better.  A new FDE in the data stream will overwrite the existing FDE in the parser which *should* make calling Reset() unnecessary though it was already exported if someone wanted to make sure and call between data source switches.

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @apokalyptik 

Parsing events from an offset in a file may cause panic because we don't have FDE information. see https://github.com/siddontang/go-mysql/issues/127

But I have no time to think how to fix it, maybe we must read FDE at first then parse from the offset.

**Comment by apokalyptik** [comment]
Right. The FDE is necessary because it tells you how to parse the headers for all other events. But once you have it you don't need it again until there's a possibility of it changing (eg a new binary log file)

My use case is drip feeding the parser data from binary log files as a source one piece at a time. As long as there is an FDE at the beginning My patch works fine. As you noted, there's no way around needing the FDE at the onset, which is a requirement that I'm not trying to get around. 

I did notice that as new FDE events come in they will replace old ones. So it should be safe to just continuously feed in data from file after file since, the new file will provide an updated FDE at the beginning, as long as you skip the magic 4 bytes at the beginning of each file. 

What I'm looking at doing is this:

```go
var tmpBuf = new(bytes.Buffer)
var fp *os.File
for {
  // possibly open new file, skip 4 bytes if so
  io.CopyN(tmpBuf, fp, newIOThreadPosition)
  err = parser.ParseDataFromReader(tmpBuf, func(event *replication.BinlogEvent) error {
    //  ...
  })
  tmpBuf.Truncate(0)
}
```

Because I have the requirement that I need to keep pace with the Replication IO thread. Which necessitated the drip feeding. I would use ParseReader() for this but the p.Reset() call clears out the FDE.  I considered saving the FDE to simply continuously prepend to the tmpBuf but the raw bytes on the Event doesn't actually include the envelope, only the event described by the envelope... And I didn't want to get too invasive in your code if possible :)

**Comment by siddontang** [comment]
@apokalyptik 

Maybe the easiest way is to remove Reset in ParseReader. I find no side effect now.

**Comment by apokalyptik** [comment]
@siddontang I'm actually really happy with that solution. It's what I was going to do originally but I did a blame and saw it was attached to a nebulous bug report with little in the way of details. So I decided not to possibly submit a regression. I will submit a new pull. Thanks for the feedback!

**Pull request closed without merging**
