### PR TITLE
Unsigned decimal fix

### PR DESCRIPTION
**Pull request by perepechaev**

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @perepechaev , can you show me another test with table schema defined and a real query (like insert into tbl values ) ?

**Comment by siddontang** [comment]
Sorry for the late response, I just have a long vacation for Chinese Spring Festive. :smile:

**Comment by siddontang** [comment]
@perepechaev , I just try to fix new decimal bug, but not use your code here. The old parsing way for new decimal is referred from python-mysql-replication and mysql decimal, sorry that I could not understand your below code:

```
for i := 0; i < binSize; i++ {
	data[pos+i] ^= 0xff
}
```

btw, you can checkout the newest master and help me test again.

Thank you.

**Comment by perepechaev** [comment]
my tests pass with your changes

my magic: http://play.golang.org/p/F0xzh1ikdm

**Comment by siddontang** [comment]
:smile:

**Pull request closed without merging**
